/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreakCountResponse
 */
export interface StreakCountResponse {
    /**
     * 
     * @type {number}
     * @memberof StreakCountResponse
     */
    userNo?: number;
    /**
     * 
     * @type {number}
     * @memberof StreakCountResponse
     */
    streakCount?: number;
}

/**
 * Check if a given object implements the StreakCountResponse interface.
 */
export function instanceOfStreakCountResponse(value: object): value is StreakCountResponse {
    return true;
}

export function StreakCountResponseFromJSON(json: any): StreakCountResponse {
    return StreakCountResponseFromJSONTyped(json, false);
}

export function StreakCountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreakCountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userNo': json['userNo'] == null ? undefined : json['userNo'],
        'streakCount': json['streakCount'] == null ? undefined : json['streakCount'],
    };
}

export function StreakCountResponseToJSON(json: any): StreakCountResponse {
    return StreakCountResponseToJSONTyped(json, false);
}

export function StreakCountResponseToJSONTyped(value?: StreakCountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userNo': value['userNo'],
        'streakCount': value['streakCount'],
    };
}

