/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRequest
 */
export interface UpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateRequest
     */
    profileImage?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRequest
     */
    gender?: UpdateRequestGenderEnum;
    /**
     * 
     * @type {Date}
     * @memberof UpdateRequest
     */
    birthDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof UpdateRequest
     */
    password?: string;
}


/**
 * @export
 */
export const UpdateRequestGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Other: 'OTHER'
} as const;
export type UpdateRequestGenderEnum = typeof UpdateRequestGenderEnum[keyof typeof UpdateRequestGenderEnum];


/**
 * Check if a given object implements the UpdateRequest interface.
 */
export function instanceOfUpdateRequest(value: object): value is UpdateRequest {
    return true;
}

export function UpdateRequestFromJSON(json: any): UpdateRequest {
    return UpdateRequestFromJSONTyped(json, false);
}

export function UpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'profileImage': json['profileImage'] == null ? undefined : json['profileImage'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UpdateRequestToJSON(json: any): UpdateRequest {
    return UpdateRequestToJSONTyped(json, false);
}

export function UpdateRequestToJSONTyped(value?: UpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profileImage': value['profileImage'],
        'gender': value['gender'],
        'birthDate': value['birthDate'] == null ? undefined : ((value['birthDate']).toISOString().substring(0,10)),
        'password': value['password'],
    };
}

