import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import AuthSessionProvider from '@/components/ui/provider/session-provider';
import './globals.css';
import { ModalProvider } from '@/components/ui/modal/modal.context';
import { ModalRegistry } from '@/components/ui/modal/modal-registry';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthSessionProvider>
          <ModalProvider
            registry={ModalRegistry}
            defaultOverlayOptions={{ default: { closeDelay: 500 } }}
          >
            {children}
          </ModalProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
