/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class OpenAIApi extends runtime.BaseAPI {

    /**
     * ChatGPT API와의 연결 상태를 확인합니다. 개발 및 디버깅용입니다.
     * OpenAI API 연결 테스트
     */
    async testOpenAiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/test/openai`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * ChatGPT API와의 연결 상태를 확인합니다. 개발 및 디버깅용입니다.
     * OpenAI API 연결 테스트
     */
    async testOpenAi(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.testOpenAiRaw(initOverrides);
        return await response.value();
    }

}
