/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadgeResponse
 */
export interface BadgeResponse {
    /**
     * 
     * @type {number}
     * @memberof BadgeResponse
     */
    badgeId?: number;
    /**
     * 
     * @type {string}
     * @memberof BadgeResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BadgeResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof BadgeResponse
     */
    conditionJson?: string;
}

/**
 * Check if a given object implements the BadgeResponse interface.
 */
export function instanceOfBadgeResponse(value: object): value is BadgeResponse {
    return true;
}

export function BadgeResponseFromJSON(json: any): BadgeResponse {
    return BadgeResponseFromJSONTyped(json, false);
}

export function BadgeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadgeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'badgeId': json['badgeId'] == null ? undefined : json['badgeId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'conditionJson': json['conditionJson'] == null ? undefined : json['conditionJson'],
    };
}

export function BadgeResponseToJSON(json: any): BadgeResponse {
    return BadgeResponseToJSONTyped(json, false);
}

export function BadgeResponseToJSONTyped(value?: BadgeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'badgeId': value['badgeId'],
        'name': value['name'],
        'description': value['description'],
        'conditionJson': value['conditionJson'],
    };
}

