/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadgeRequest
 */
export interface BadgeRequest {
    /**
     * 
     * @type {string}
     * @memberof BadgeRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof BadgeRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof BadgeRequest
     */
    conditionJson?: string;
}

/**
 * Check if a given object implements the BadgeRequest interface.
 */
export function instanceOfBadgeRequest(value: object): value is BadgeRequest {
    return true;
}

export function BadgeRequestFromJSON(json: any): BadgeRequest {
    return BadgeRequestFromJSONTyped(json, false);
}

export function BadgeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadgeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'conditionJson': json['conditionJson'] == null ? undefined : json['conditionJson'],
    };
}

export function BadgeRequestToJSON(json: any): BadgeRequest {
    return BadgeRequestToJSONTyped(json, false);
}

export function BadgeRequestToJSONTyped(value?: BadgeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'conditionJson': value['conditionJson'],
    };
}

