/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRequest
 */
export interface CreateRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRequest
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRequest
     */
    kakaoId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRequest
     */
    profileImage?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateRequest
     */
    gender?: CreateRequestGenderEnum;
    /**
     * 
     * @type {Date}
     * @memberof CreateRequest
     */
    birthDate?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRequest
     */
    kakaoSignup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateRequest
     */
    generalSignup?: boolean;
}


/**
 * @export
 */
export const CreateRequestGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Other: 'OTHER'
} as const;
export type CreateRequestGenderEnum = typeof CreateRequestGenderEnum[keyof typeof CreateRequestGenderEnum];


/**
 * Check if a given object implements the CreateRequest interface.
 */
export function instanceOfCreateRequest(value: object): value is CreateRequest {
    return true;
}

export function CreateRequestFromJSON(json: any): CreateRequest {
    return CreateRequestFromJSONTyped(json, false);
}

export function CreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'password': json['password'] == null ? undefined : json['password'],
        'kakaoId': json['kakaoId'] == null ? undefined : json['kakaoId'],
        'profileImage': json['profileImage'] == null ? undefined : json['profileImage'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'kakaoSignup': json['kakaoSignup'] == null ? undefined : json['kakaoSignup'],
        'generalSignup': json['generalSignup'] == null ? undefined : json['generalSignup'],
    };
}

export function CreateRequestToJSON(json: any): CreateRequest {
    return CreateRequestToJSONTyped(json, false);
}

export function CreateRequestToJSONTyped(value?: CreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'password': value['password'],
        'kakaoId': value['kakaoId'],
        'profileImage': value['profileImage'],
        'gender': value['gender'],
        'birthDate': value['birthDate'] == null ? undefined : ((value['birthDate']).toISOString().substring(0,10)),
        'kakaoSignup': value['kakaoSignup'],
        'generalSignup': value['generalSignup'],
    };
}

