/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 카카오 로그인 요청 DTO
 * @export
 * @interface KakaoLoginRequest
 */
export interface KakaoLoginRequest {
    /**
     * 카카오에서 제공하는 사용자 고유 ID
     * @type {string}
     * @memberof KakaoLoginRequest
     */
    kakaoId: string;
    /**
     * 카카오 프로필에서 가져온 닉네임 (중복시 자동으로 숫자가 붙습니다)
     * @type {string}
     * @memberof KakaoLoginRequest
     */
    nickname: string;
    /**
     * 카카오 프로필 이미지 URL (선택사항, 없으면 null 또는 생략 가능)
     * @type {string}
     * @memberof KakaoLoginRequest
     */
    profileImage?: string | null;
}

/**
 * Check if a given object implements the KakaoLoginRequest interface.
 */
export function instanceOfKakaoLoginRequest(value: object): value is KakaoLoginRequest {
    if (!('kakaoId' in value) || value['kakaoId'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    return true;
}

export function KakaoLoginRequestFromJSON(json: any): KakaoLoginRequest {
    return KakaoLoginRequestFromJSONTyped(json, false);
}

export function KakaoLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): KakaoLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'kakaoId': json['kakaoId'],
        'nickname': json['nickname'],
        'profileImage': json['profileImage'] == null ? undefined : json['profileImage'],
    };
}

export function KakaoLoginRequestToJSON(json: any): KakaoLoginRequest {
    return KakaoLoginRequestToJSONTyped(json, false);
}

export function KakaoLoginRequestToJSONTyped(value?: KakaoLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kakaoId': value['kakaoId'],
        'nickname': value['nickname'],
        'profileImage': value['profileImage'],
    };
}

