/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    userNo?: number;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    expiresIn?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponse
     */
    kakaoUser?: boolean;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'userNo': json['userNo'] == null ? undefined : json['userNo'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
        'kakaoUser': json['kakaoUser'] == null ? undefined : json['kakaoUser'],
    };
}

export function LoginResponseToJSON(json: any): LoginResponse {
    return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(value?: LoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'userNo': value['userNo'],
        'nickname': value['nickname'],
        'accessToken': value['accessToken'],
        'expiresIn': value['expiresIn'],
        'kakaoUser': value['kakaoUser'],
    };
}

