/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuizResultSummary
 */
export interface QuizResultSummary {
    /**
     * 
     * @type {boolean}
     * @memberof QuizResultSummary
     */
    allCorrect?: boolean;
    /**
     * 
     * @type {number}
     * @memberof QuizResultSummary
     */
    totalSolved?: number;
    /**
     * 
     * @type {number}
     * @memberof QuizResultSummary
     */
    correctCount?: number;
}

/**
 * Check if a given object implements the QuizResultSummary interface.
 */
export function instanceOfQuizResultSummary(value: object): value is QuizResultSummary {
    return true;
}

export function QuizResultSummaryFromJSON(json: any): QuizResultSummary {
    return QuizResultSummaryFromJSONTyped(json, false);
}

export function QuizResultSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizResultSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'allCorrect': json['allCorrect'] == null ? undefined : json['allCorrect'],
        'totalSolved': json['totalSolved'] == null ? undefined : json['totalSolved'],
        'correctCount': json['correctCount'] == null ? undefined : json['correctCount'],
    };
}

export function QuizResultSummaryToJSON(json: any): QuizResultSummary {
    return QuizResultSummaryToJSONTyped(json, false);
}

export function QuizResultSummaryToJSONTyped(value?: QuizResultSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allCorrect': value['allCorrect'],
        'totalSolved': value['totalSolved'],
        'correctCount': value['correctCount'],
    };
}

