/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuizSubmitRequest
 */
export interface QuizSubmitRequest {
    /**
     * 
     * @type {number}
     * @memberof QuizSubmitRequest
     */
    quizId?: number;
    /**
     * 
     * @type {string}
     * @memberof QuizSubmitRequest
     */
    userAnswer?: string;
    /**
     * 
     * @type {boolean}
     * @memberof QuizSubmitRequest
     */
    skipped?: boolean;
}

/**
 * Check if a given object implements the QuizSubmitRequest interface.
 */
export function instanceOfQuizSubmitRequest(value: object): value is QuizSubmitRequest {
    return true;
}

export function QuizSubmitRequestFromJSON(json: any): QuizSubmitRequest {
    return QuizSubmitRequestFromJSONTyped(json, false);
}

export function QuizSubmitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizSubmitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quizId': json['quizId'] == null ? undefined : json['quizId'],
        'userAnswer': json['userAnswer'] == null ? undefined : json['userAnswer'],
        'skipped': json['skipped'] == null ? undefined : json['skipped'],
    };
}

export function QuizSubmitRequestToJSON(json: any): QuizSubmitRequest {
    return QuizSubmitRequestToJSONTyped(json, false);
}

export function QuizSubmitRequestToJSONTyped(value?: QuizSubmitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quizId': value['quizId'],
        'userAnswer': value['userAnswer'],
        'skipped': value['skipped'],
    };
}

