/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuizResponse
 */
export interface QuizResponse {
    /**
     * 
     * @type {number}
     * @memberof QuizResponse
     */
    quizId?: number;
    /**
     * 
     * @type {string}
     * @memberof QuizResponse
     */
    context?: string;
    /**
     * 
     * @type {string}
     * @memberof QuizResponse
     */
    question?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof QuizResponse
     */
    choices?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof QuizResponse
     */
    answer?: string;
}

/**
 * Check if a given object implements the QuizResponse interface.
 */
export function instanceOfQuizResponse(value: object): value is QuizResponse {
    return true;
}

export function QuizResponseFromJSON(json: any): QuizResponse {
    return QuizResponseFromJSONTyped(json, false);
}

export function QuizResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'quizId': json['quizId'] == null ? undefined : json['quizId'],
        'context': json['context'] == null ? undefined : json['context'],
        'question': json['question'] == null ? undefined : json['question'],
        'choices': json['choices'] == null ? undefined : json['choices'],
        'answer': json['answer'] == null ? undefined : json['answer'],
    };
}

export function QuizResponseToJSON(json: any): QuizResponse {
    return QuizResponseToJSONTyped(json, false);
}

export function QuizResponseToJSONTyped(value?: QuizResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quizId': value['quizId'],
        'context': value['context'],
        'question': value['question'],
        'choices': value['choices'],
        'answer': value['answer'],
    };
}

