/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordCreateRequest
 */
export interface RecordCreateRequest {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof RecordCreateRequest
     */
    answers?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof RecordCreateRequest
     */
    emotion?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RecordCreateRequest
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the RecordCreateRequest interface.
 */
export function instanceOfRecordCreateRequest(value: object): value is RecordCreateRequest {
    return true;
}

export function RecordCreateRequestFromJSON(json: any): RecordCreateRequest {
    return RecordCreateRequestFromJSONTyped(json, false);
}

export function RecordCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'answers': json['answers'] == null ? undefined : json['answers'],
        'emotion': json['emotion'] == null ? undefined : json['emotion'],
        'valid': json['valid'] == null ? undefined : json['valid'],
    };
}

export function RecordCreateRequestToJSON(json: any): RecordCreateRequest {
    return RecordCreateRequestToJSONTyped(json, false);
}

export function RecordCreateRequestToJSONTyped(value?: RecordCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answers': value['answers'],
        'emotion': value['emotion'],
        'valid': value['valid'],
    };
}

