/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Response
 */
export interface Response {
    /**
     * 
     * @type {number}
     * @memberof Response
     */
    userNo?: number;
    /**
     * 
     * @type {string}
     * @memberof Response
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof Response
     */
    profileImage?: string;
    /**
     * 
     * @type {string}
     * @memberof Response
     */
    gender?: ResponseGenderEnum;
    /**
     * 
     * @type {Date}
     * @memberof Response
     */
    birthDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof Response
     */
    streakCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof Response
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Response
     */
    updatedAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Response
     */
    kakaoUser?: boolean;
}


/**
 * @export
 */
export const ResponseGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Other: 'OTHER'
} as const;
export type ResponseGenderEnum = typeof ResponseGenderEnum[keyof typeof ResponseGenderEnum];


/**
 * Check if a given object implements the Response interface.
 */
export function instanceOfResponse(value: object): value is Response {
    return true;
}

export function ResponseFromJSON(json: any): Response {
    return ResponseFromJSONTyped(json, false);
}

export function ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Response {
    if (json == null) {
        return json;
    }
    return {
        
        'userNo': json['userNo'] == null ? undefined : json['userNo'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'profileImage': json['profileImage'] == null ? undefined : json['profileImage'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'streakCount': json['streakCount'] == null ? undefined : json['streakCount'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'kakaoUser': json['kakaoUser'] == null ? undefined : json['kakaoUser'],
    };
}

export function ResponseToJSON(json: any): Response {
    return ResponseToJSONTyped(json, false);
}

export function ResponseToJSONTyped(value?: Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userNo': value['userNo'],
        'nickname': value['nickname'],
        'profileImage': value['profileImage'],
        'gender': value['gender'],
        'birthDate': value['birthDate'] == null ? undefined : ((value['birthDate']).toISOString().substring(0,10)),
        'streakCount': value['streakCount'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'kakaoUser': value['kakaoUser'],
    };
}

