/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkipStatusResponse
 */
export interface SkipStatusResponse {
    /**
     * 
     * @type {number}
     * @memberof SkipStatusResponse
     */
    skippedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkipStatusResponse
     */
    remainingSkips?: number;
}

/**
 * Check if a given object implements the SkipStatusResponse interface.
 */
export function instanceOfSkipStatusResponse(value: object): value is SkipStatusResponse {
    return true;
}

export function SkipStatusResponseFromJSON(json: any): SkipStatusResponse {
    return SkipStatusResponseFromJSONTyped(json, false);
}

export function SkipStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkipStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skippedCount': json['skippedCount'] == null ? undefined : json['skippedCount'],
        'remainingSkips': json['remainingSkips'] == null ? undefined : json['remainingSkips'],
    };
}

export function SkipStatusResponseToJSON(json: any): SkipStatusResponse {
    return SkipStatusResponseToJSONTyped(json, false);
}

export function SkipStatusResponseToJSONTyped(value?: SkipStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skippedCount': value['skippedCount'],
        'remainingSkips': value['remainingSkips'],
    };
}

