/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBadgeRequest
 */
export interface UserBadgeRequest {
    /**
     * 
     * @type {number}
     * @memberof UserBadgeRequest
     */
    userNo?: number;
    /**
     * 
     * @type {number}
     * @memberof UserBadgeRequest
     */
    badgeId?: number;
}

/**
 * Check if a given object implements the UserBadgeRequest interface.
 */
export function instanceOfUserBadgeRequest(value: object): value is UserBadgeRequest {
    return true;
}

export function UserBadgeRequestFromJSON(json: any): UserBadgeRequest {
    return UserBadgeRequestFromJSONTyped(json, false);
}

export function UserBadgeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBadgeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userNo': json['userNo'] == null ? undefined : json['userNo'],
        'badgeId': json['badgeId'] == null ? undefined : json['badgeId'],
    };
}

export function UserBadgeRequestToJSON(json: any): UserBadgeRequest {
    return UserBadgeRequestToJSONTyped(json, false);
}

export function UserBadgeRequestToJSONTyped(value?: UserBadgeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userNo': value['userNo'],
        'badgeId': value['badgeId'],
    };
}

