/* tslint:disable */
/* eslint-disable */
/**
 * Thinkeep API
 * 일기 작성 및 관리 API 문서
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@thinkeep.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBadgeResponse
 */
export interface UserBadgeResponse {
    /**
     * 
     * @type {number}
     * @memberof UserBadgeResponse
     */
    userNo?: number;
    /**
     * 
     * @type {number}
     * @memberof UserBadgeResponse
     */
    badgeId?: number;
    /**
     * 
     * @type {Date}
     * @memberof UserBadgeResponse
     */
    awardedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof UserBadgeResponse
     */
    streakCount?: number;
}

/**
 * Check if a given object implements the UserBadgeResponse interface.
 */
export function instanceOfUserBadgeResponse(value: object): value is UserBadgeResponse {
    return true;
}

export function UserBadgeResponseFromJSON(json: any): UserBadgeResponse {
    return UserBadgeResponseFromJSONTyped(json, false);
}

export function UserBadgeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBadgeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userNo': json['userNo'] == null ? undefined : json['userNo'],
        'badgeId': json['badgeId'] == null ? undefined : json['badgeId'],
        'awardedAt': json['awardedAt'] == null ? undefined : (new Date(json['awardedAt'])),
        'streakCount': json['streakCount'] == null ? undefined : json['streakCount'],
    };
}

export function UserBadgeResponseToJSON(json: any): UserBadgeResponse {
    return UserBadgeResponseToJSONTyped(json, false);
}

export function UserBadgeResponseToJSONTyped(value?: UserBadgeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userNo': value['userNo'],
        'badgeId': value['badgeId'],
        'awardedAt': value['awardedAt'] == null ? undefined : ((value['awardedAt']).toISOString()),
        'streakCount': value['streakCount'],
    };
}

